### PR TITLE
add JuliaFormatter to Github Workflows

### LINKED ISSUE #238: Julia Formatter
As other popular libraries do, I would suggest adding a [Julia Formatter](https://domluna.github.io/JuliaFormatter.jl/dev/config/).

### PR DESCRIPTION
**Pull request by pri1311**
Hi, this PR aims to add JuliaFormatter to GitHub workflows.

Closes #238 

I have adapted most of the code from [OrdinaryDiffEq.jl](https://github.com/SciML/OrdinaryDiffEq.jl/blob/master/.github/workflows/FormatCheck.yml) and made a few changes. 

I haven't added any specific options to the [.JuliaFormatter.toml](https://github.com/CarloLucibello/GraphNeuralNetworks.jl/compare/master...pri1311:GraphNeuralNetworks.jl:juliaformatter?expand=1#diff-5f67c85b9d4e42447b057e74bdfae39f20694747f0e10634cdb9d2e35f8ef217) yet. I would appreciate it if you could point out the specifics for the code style GraphNeuralNetworks.jl follows from the list of [options](https://github.com/domluna/JuliaFormatter.jl/blob/master/src/options.jl), if any.

Thanks.

### CODE REVIEW

**Comment by Dsantra92** [comment]
The formatting checks are failing because some files are not formatted. Can you format the locally and commit them? Also  do we need two format checks?

**Comment by Dsantra92** [comment]
Also add the code-style to Readme like [SciML](https://github.com/SciML/OrdinaryDiffEq.jl/blob/master/README.md)?

**Comment by CarloLucibello** [comment]
Reminder for myself:
after merging this, create a `.git-blame-ignore-revs` file
https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view

**Comment by Dsantra92** [comment]
LGTM

**Comment by Dsantra92** [comment]
Also, this also triggers non-cache documentation :(. Need to fix this too here.

**Comment by pri1311** [comment]
@Dsantra92 I am having trouble understanding the issue here. could you elaborate on it?

**Comment by Dsantra92** [comment]
Can you use Julia 1.8.2 for rendering instead of 1.8? Looks like cache didn't work.

**Comment by Dsantra92** [comment]
Nice work! The documentation cache for Pluto is working perfectly.

**Comment by CarloLucibello** [comment]
Thanks both for looking into this!

**Pull request merged**
