### PR TITLE
Replace depreciated Flux.ADAM with Flux.Adam

### PR DESCRIPTION
**Pull request by mplemay**
This PR replaces the depreciated `Flux.ADAM` optimizer with `Flux.Adam` across the entire project. This PR only changes, docs, performance benchmarks, tests, and examples so it should it should have not break end-user code.

### CODE REVIEW

**Comment by mplemay** [comment]
@CarloLucibello I just noticed you created another PR that addresses this. I will close this.

**Comment by CarloLucibello** [comment]
I actually I would prefer if we merge this PR instead of having an unrelated change in another PR

**Comment by CarloLucibello** [comment]
We need to update Flux compat to 0.13.4

**Comment by mplemay** [comment]
> We need to update Flux compat to 0.13.4

@CarloLucibello I am relatively new to Julia. In this case would it make more sense to set the compatibility to `^0.13.4` or `~0.13.4`?

**Comment by CarloLucibello** [comment]
See how it is done in #202

**Pull request merged**
