### PR TITLE
feat: Add SGConv support for HeteroGraphConv 

### PR DESCRIPTION
**Pull request by askorupka**
This PR adds SGConv support for HeteroGraphConv.
This is related to issue https://github.com/CarloLucibello/GraphNeuralNetworks.jl/issues/311.

### CODE REVIEW

**Comment by rbSparky** [comment]
PR #383

**Comment by CarloLucibello** [comment]
this is already being taken care of

**Comment by askorupka** [comment]
Sorry but I don't support decision regarding closing working PR. The other PR was a draft with commits and unfinished work (not the best practice to block others' work) and this PR was working and passing tests. Now I see my code implemented in the other PR without my commits/contribution. One could at least rebase against my branch.
FYI @CarloLucibello @rbSparky

**Comment by CarloLucibello** [comment]
As you can see from the discussion in #383 and from the merged commit 
https://github.com/CarloLucibello/GraphNeuralNetworks.jl/commit/64b3cbb6f9e80287043ff573fd8a4a87219cc0dc
you have been properly credited.

**Pull request closed without merging**
