### PR TITLE
Add new cache for changed notebooks!

### PR DESCRIPTION
**Pull request by Dsantra92**
We need to commit the cache notebooks every time we make some changes to the pluto notebooks. This pr refreshes cache files for changes made in #245. We should mention somewhere how to contribute to docs.

### CODE REVIEW

**Comment by CarloLucibello** [comment]
Thanks! It would be great if you could add a section about caching tutorials in the Developer Notes of the docs

**Comment by Dsantra92** [comment]
> Thanks! It would be great if you could add a section about caching tutorials in the Developer Notes of the docs

Yes, that's a good idea.

**Comment by Dsantra92** [comment]
docs-usage

Needed for usage in the docs ✌🏾

**Comment by CarloLucibello** [comment]
thanks!

**Pull request merged**
